import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState } from 'react';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>SISTECH Final Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      

  <video autoPlay loop muted>
    <source src="https://cdn.dribbble.com/users/11653188/screenshots/18227063/media/84aea3be4bb55990b95054d7551a6208.mp4" type="video/mp4"> 
  </source>
  
  </video>

  <div className="bubbly-text">Bubble of your thoughts</div>
  <div className="subtext">Your place to express and share your ideas.</div>

  <a href="/blog" className="start-button">Start bubbling</a>
      </main>
    </>
  )
}
